### PR TITLE
task 1 completed

### PR DESCRIPTION
**Pull request by choudharysneha1708**

### CODE REVIEW

**Comment by raghavgoel25** [comment]
@choudharysneha1708 why have you modified Bharat-1919.txt?

**Comment by choudharysneha1708** [comment]
Sir it was my mistake

**Comment by shashwat-mittal** [comment]
@choudharysneha1708 Don't try to put unnecessary files..

**Comment by shashwat-mittal** [comment]
This time it has been deleted but from next time you would have to redo the task..

**Pull request merged**
