### PR TITLE
Udayasree-Banothu444 Completed task 1

### PR DESCRIPTION
**Pull request by Udayasree-Banothu444**
issue:1

### CODE REVIEW

**Comment by shashwat-mittal** [comment]
you had to create a .txt file with some details in the folder Omicron_Batch..
Instead you have pushed some pdf..
Please delete the pdf and create the .txt file and than push it..

**Comment by Udayasree-Banothu444** [comment]
Respected sir,
Sir i am udayasree, I am unable to send pull request... Can please explain
me how to do that... Thank u sir

**Comment by shashwat-mittal** [comment]
@Udayasree-Banothu444 i guess you did not change the branch to subtask1 while making the pull request..
When you are making the pull request please change both the branches from main to subtask1..

**Comment by Udayasree-Banothu444** [comment]
Thank you sir for your response... Sir, I have a doubt, I am unable to
complete the task in the given time...it make any difference if I do not
complete the task in the given time...

**Comment by Udayasree-Banothu444** [comment]
I would like make a new pull request

**Comment by Udayasree-Banothu444** [comment]
i will make new one

**Pull request closed without merging**
