### PR TITLE
Tushar-2k21 Completed task 1

### PR DESCRIPTION
**Pull request by Tushar-2k21**

### CODE REVIEW

**Comment by medhatiwari** [comment]
Hey you don't have to delete `shashwat-mittal.txt`. Please add it again

**Comment by Tushar-2k21** [comment]
> 

how to do that maam?

**Comment by medhatiwari** [comment]
> > 
> 
> how to do that maam?

join vc

**Comment by Tushar-2k21** [comment]
Maam what do you mean by vc?

**Pull request merged**
